### ISSUE TITLE
Make links work

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#147]
Registration button on home page
Registration button in navbar
Login button in navbar
Clicking profile icon in navbar
etc.

**Comment by NeoLou** [comment]
A couple of questions:
- Is the "Register" button on the home page and in the navbar supposed to bring you to the registration form page?
- Are you only allowed to register once you're logged in? What happens when you're logged in vs when you're not logged in?
- How is the profile icon supposed to work? Are you able to click on it when you're not logged in or only when you're logged in?
- Also, how do we test a functionality that only works when we login?

**Comment by jameskokoska** [comment]
> A couple of questions:
> - Is the "Register" button on the home page and in the navbar supposed to bring you to the registration form page?

So if they're not logged in, it should bring them to the create account page
If they are, it should bring them to the registration form 
aside: Once the Frosh create an account, they have the button to register 

> - Are you only allowed to register once you're logged in? What happens when you're logged in vs when you're not logged in?

If the Frosh is already registered fully, ideally we have the button hidden


> - How is the profile icon supposed to work? Are you able to click on it when you're not logged in or only when you're logged in?

When they are logged in, the user profile icon should change to their initials
If they click it when they are not logged in, it should go the the login page 

> - Also, how do we test a functionality that only works when we login?

If i understand your question,
Someone will need to setup routes that are only accessible if you are logged in
For e.g. if someone tries accessing the profile page when not logged in, it should redirect them to the login page
This will probably be a later problem and should be submitted as a separate ticket
Please create a ticket

**Comment by lukewarmtemp** [comment]
![Login_Buttons](https://user-images.githubusercontent.com/74154406/176569365-2c94505b-2d58-47e8-8e65-dbe3401fed44.PNG)
The login button appears twice.
