### ISSUE TITLE
When submitting an FAQ, the email fields gets wiped

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#321]
Shouldn't be cleared

**Comment by lukewarmtemp** [comment]
The error/success message button also persists even after the form is closed and opened again. It should be cleared.

**Comment by lukewarmtemp** [comment]
@jameskokoska The contents of the ask question pop-up also persist if the form is closed before submitting. I don't think we should clear the contents because users might need to reference a certain part of the page to complete what they want to write. Not clearing the content allows users to continue on where they left off if they need to look at something again on the page. Therefore, I think we shouldn't change this.

**Comment by jameskokoska** [comment]
Closed via https://github.com/UofT-Frosh-Orientation/orientation-website/pull/358/commits/1a812c36712a50824f860de1ffa14c67a18e7218 in https://github.com/UofT-Frosh-Orientation/orientation-website/pull/358
