### ISSUE TITLE
Edit profile page for non registered users

### ISSUE THREAD

**Issue by jameskokoska** [UofT-Frosh-Orientation/orientation-website#353]
So they can edit firstName, lastName, email, preferredName without creating an account

**Comment by Freeassassin** [comment]
## **Expected Behavior:**

Users should be able to edit their basic info such as firstName, lastName, preferredName after creating an account that is not fully registered for F!rosh Week.

## **Requirements:**

- [ ] Create a profile edit page. 
- [ ] Implement backend routes in `userRoutes.js` 

## **External Factors:**

N/a

## **Related Issues/PRs:**

- Similar to #465 for changing user data when unsubscribing from emails.

## **Resources:**

Contact @Freeassassin if you need help with working with the backend.

### **Tutorials:**

- [35 Minute Express.js Tutorial](https://www.youtube.com/watch?v=SccSCuHhOw0)
- [REST API Explainer Video through Express.js](https://www.youtube.com/watch?v=-MTSQjw5DrM)
- [Middleware Explainer Video](https://www.youtube.com/watch?v=lY6icfhap2o)

### **Documentation:**

- [Mongoose Docs](https://mongoosejs.com/docs/)
- [Internal Backend Documentation](https://docs.orientation.skule.ca/pages/Onboarding/Backend.html)
